### PR TITLE
Update dependencies, fix incompatibility with image 0.24

### LINKED ISSUE #52: Add support for `image-rs 0.24`
Since the latest version of image-rs library require Rust 1.56.0, I think that img_hash also should use Rust 2021 edition and bump minimal requirements.

For now I can't use image-rs 0.24.0, because img_hash crate cannot interoperate with this version and I have such errors(this works with 0.23)
```
error[E0277]: the trait bound `image::DynamicImage: Image` is not satisfied
   --> czkawka_core/src/similar_images.rs:606:50
    |
606 |                     let hash = hasher.hash_image(&image);
    |                                       ---------- ^^^^^^ the trait `Image` is not implemented for `image::DynamicImage`
    |                                       |
    |                                       required by a bound introduced by this call
```

### PR DESCRIPTION
**Pull request by lovasoa**
Fixes https://github.com/abonander/img_hash/issues/52

### CODE REVIEW

**Comment by nicoulaj** [comment]
@lovasoa your PR contains the whole renaming to `image_hasher`

**Comment by avasilic** [comment]
@lovasoa Is this still being maintained?

**Comment by lovasoa** [comment]
no :grimacing:
